name: Lighthouse CI Mobile
on: 
  pull_request:
      branches:
        - master
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@v9
      env:
        URL_DOMAIN: 'www.niagahoster.co.id'
      with:
        urls: |
          https://$URL_DOMAIN/reseller-hosting
          https://$URL_DOMAIN/afiliasi
        configPath: '.github/lighthouse/mobile-lighthouserc.json'
        budgetPath: '.github/lighthouse/mobile-budget.json'
        uploadArtifacts: true
        temporaryPublicStorage: true
